#!/bin/sh

test -z $1 && exit 1
clear

bin/lobster --pak $1
cd dev/emscripten

cp $(dirname $1)/default.lpak assets
mkdir -p assets/data
mkdir -p assets/data/shaders
cp ../../data/shaders/default.materials assets/data/shaders/
ls assets

INP=
echo run? && read -r $INP
/usr/lib/emscripten/emrun --browser firefox lobster.html --verbose
